# Generated by Django 5.1.2 on 2025-11-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_movie_details_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_details',
            name='rating',
            field=models.CharField(max_length=100),
        ),
    ]
